steps:
  - name: docker/compose:1.29.0
    args:
      - -f
      - main-project/backend/docker-compose.yaml
      - build

  - name: docker/compose:1.29.0
    args:
      - -f
      - main-project/backend/docker-compose.yaml
      - push

  - name: "gcr.io/cloud-builders/kubectl"
    args:
      [
        "set",
        "image",
        "deployment/my-backend",
        "main-project-sha256-1=asia.gcr.io/main-project-leokim1178/main-project:0.01.8",
      ]
    env:
      - CLOUDSDK_COMPUTE_ZONE=asia-northeast3
      - CLOUDSDK_CONTAINER_CLUSTER=leo-mp-cluster

  - name: "gcr.io/cloud-builders/kubectl"
    args:
      [
        "set",
        "image",
        "deployment/my-logstash",
        "my-logstash-sha256-1=asia.gcr.io/main-project-leokim1178/my-logstash:0.00.3",
      ]
    env:
      - CLOUDSDK_COMPUTE_ZONE=asia-northeast3
      - CLOUDSDK_CONTAINER_CLUSTER=leo-mp-cluster
